services:
  # A Docker web service
  - type: web
    name: keybert-api
    runtime: python-3.10.10
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k uvicorn.workers.UvicornWorker main:app
